### ISSUE TITLE
Docs are incorrect in a few places

### ISSUE THREAD

**Issue by nhouck** [scaleflex/vue-cloudimage-responsive#1]
Please update section 2 of the docs, it doesn't reflect the current code.

CloudimageProvider should be CloudImageProvider - capital I.

<CloudImageProvider :cloudImageConfig="cloudimageConfig">

Also this section

```
<template>
<CloudimageProvider config={cloudimageConfig}>
 <h1>Simple demo of vue-cloudimage-responsive</h1>
<Img src="img.jpg" alt="Demo image" ratio=1.5 />
</CloudimageProvider>
</template>
```

should be

```
<template>
  <div id="app">
    <CloudImageProvider :cloudImageConfig="cloudimageConfig">
      <h1>Simple demo of vue-cloudimage-responsive</h1>
      <Img src="img.jpg" alt="Demo image"/>
    </CloudImageProvider>
  </div>
</template>
```

This is missing

```
export default {
   data() {
		return {
      cloudimageConfig,
...
```

Call out that `<Img>` tag is custom and uses capital I, just in case people don't realize it at first look.

It would be better if you used the App.vue as one file and another view teamplate SamplePage.vue which has the template in it, as generally the template code doesn't go in App.vue.  This would make it more clear what code goes where.

Docs should explain the 3 versions, what are the differences?

**Comment by amrelbialy** [comment]
Thanks for informing us we will update the documentation but for export default must be put in components object not data
